### ISSUE TITLE
build failure on debian - error: uninitialized const ‘iNsDelay’ 

### ISSUE THREAD

**Issue by dcthorson** [corrados/jamulus#41]
Compiling error with:
```bash
$ git show -s
commit bd111c3abc22b2d2b6f5634f4b9b77a6d20eef4d
Author: Volker Fischer <corrados@users.noreply.github.com>
Date:   Sun Apr 5 17:35:40 2020 +0200

    some code cleanup
```
on
```bash
$ uname -a
Linux 4.9.0-12-amd64 #1 SMP Debian 4.9.210-1 (2020-01-20) x86_64 GNU/Linuxadmin 
```

Performed these steps on AWS instance:
```
$ sudo apt update
$ sudo apt upgrade
.
perform reboot
.
$ sudo apt install build-essential
$ sudo apt install libqt4-dev
$ sudo apt-get install libjack-jackd2-dev
$ mkdir GitHub
$ cd GitHub/
$ mkdir jamulus
$ sudo apt-get install git
$ git clone https://git.code.sf.net/p/llcon/jamulus
$ cd jamulus/
$ qmake "CONFIG+=nosound" Jamulus.pro 
$ make clean
$ make
```

after a few seconds:
```
g++ -c -m64 -pipe -std=c++11 -O2 -D_REENTRANT -Wall -W -DAPP_VERSION=\"3.4.6git\" -DOPUS_BUILD -DUSE_ALLOCA -DCUSTOM_MODES -D_REENTRANT -DHAVE_LRINTF -DHAVE_STDINT_H -DQT_NO_DEBUG -DQT_XML_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtXml -I/usr/include/qt4 -Isrc -Ilibs/opus/include -Ilibs/opus/celt -Ilibs/opus/silk -Ilibs/opus/silk/float -I. -I. -o server.o src/server.cpp

src/server.cpp: In constructor ‘CHighPrecisionTimer::CHighPrecisionTimer(bool)’:
src/server.cpp:121:20: error: uninitialized const ‘iNsDelay’ [-fpermissive]
     const uint64_t iNsDelay;
                    ^~~~~~~~
In file included from src/server.h:36:0,
                 from src/server.cpp:25:
src/global.h:121:41: error: assignment of read-only variable ‘iNsDelay’
 #define SYSTEM_SAMPLE_RATE_HZ           48000 // Hz
                                         ^

src/server.cpp:126:31: note: in expansion of macro ‘SYSTEM_SAMPLE_RATE_HZ’
                    (uint64_t) SYSTEM_SAMPLE_RATE_HZ; // in ns
                               ^~~~~~~~~~~~~~~~~~~~~

src/global.h:121:41: error: assignment of read-only variable ‘iNsDelay’
 #define SYSTEM_SAMPLE_RATE_HZ           48000 // Hz
                                         ^

src/server.cpp:131:31: note: in expansion of macro ‘SYSTEM_SAMPLE_RATE_HZ’
                    (uint64_t) SYSTEM_SAMPLE_RATE_HZ; // in ns
                               ^~~~~~~~~~~~~~~~~~~~~
Makefile:1672: recipe for target 'server.o' failed
make: *** [server.o] Error 1
```

FYI:
```
$ g++ --version
g++ (Debian 6.3.0-18+deb9u1) 6.3.0 20170516
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by corrados** [comment]
Wow, you are fast. I just commited that code an hour ago :-). Thanks for reporting, I'll fix it in the next commit.

**Comment by dcthorson** [comment]
Timing is everything! Thanks for the quick response... I'll watch for the PR

**Comment by corrados** [comment]
Ok, it should work now.

**Comment by dcthorson** [comment]
Did a `git pull origin master` and it still shows up-to-date. Do I need to pull a particular branch?

**Comment by corrados** [comment]
Hm, should be there: https://github.com/corrados/jamulus/commit/fc9970f837043662a56a9da508923a6ace1df633

**Comment by dcthorson** [comment]
Wonder if there's data-propagation issues inside GitHub. I keep seeing 
```
$ git show -s --oneline
bd111c3 some code cleanup
```
so I deleted my clone, and re-cloned
```
$ rm -rf jamulus
$ git clone https://git.code.sf.net/p/llcon/jamulus
Cloning into 'jamulus'...
remote: Enumerating objects: 11532, done.
remote: Counting objects: 100% (11532/11532), done.
remote: Compressing objects: 100% (3553/3553), done.
remote: Total 11532 (delta 8693), reused 10525 (delta 7942)
Receiving objects: 100% (11532/11532), 8.75 MiB | 3.12 MiB/s, done.
Resolving deltas: 100% (8693/8693), done.
$ cd jamulus/
$ git show -s --oneline
bd111c3 some code cleanup
```
_shrug_ ??

**Comment by corrados** [comment]
Interesting. I just tried it on another PC where I already had an old Git repo, and there it works. After a git pull I can see:
root@jamulus:~/jamulus# git show -s --oneline
fc9970f (HEAD -> master, origin/master, origin/HEAD) fixed Linux compilation error

**Comment by dcthorson** [comment]
I hope AWS isn't caching Git stuff... that'd be BAD.

**Comment by dcthorson** [comment]
Realizing that the fetch URL might not be as desired?
```
$ git remote show origin
* remote origin
  Fetch URL: https://git.code.sf.net/p/llcon/jamulu
s  Push  URL: https://git.code.sf.net/p/llcon/jamulus
  HEAD branch: master
  Remote branches:
    integrate_recorder tracked
    master             tracked
    multichannel       tracked
  Local branch configured for 'git pull':
    master merges with remote master
  Local ref configured for 'git push':
    master pushes to master (up to date)
```

**Comment by corrados** [comment]
Oh, I see. You are using the Sourceforge Git repo. You must use the Github repo. The Sourceforge repo is just a copy of Github which I update from time to time. Maybe I delete the Sourceforge repo to avoid this confusion.

**Comment by dcthorson** [comment]
Might be a good idea to get rid of the SF repo. Might need some kind of a note there, though... I think a lot of the documentation on-line points to that, i.e. https://www.facebook.com/notes/jamulus-online-musicianssingers-jamming/howto-idiots-guide-to-installing-jamulus-server-on-amazon-aws-lightsail-ubuntu-i/507719749802976/

**Comment by dcthorson** [comment]
...and your own.. https://github.com/corrados/jamulus/wiki/Server---Linux

**Comment by corrados** [comment]
Thanks. We have to fix that...

**Comment by dcthorson** [comment]
Again, I appreciate all your efforts, and if I can find a way to help with coding, I will definitely try to do so.

**Comment by corrados** [comment]
Ok, the link in our Wiki is fixed now.
